spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: root
    password: 123456
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.hzfc.management: debug

hzfc:
  uploadfile:
    wordTemplate:
      path: G:/wordTest/uploadfile/wordTemplate/
  temporaryfile:
    word:
      path: G:/wordTest/file/word/
